apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests: 
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-367809
  artifacts:
    - image: fifapes123/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: fifapes123/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '**/*.js'
            dest: .
    - image: fifapes123/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest: .

